# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bots.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("bots.proto", :syntax => :proto3) do
    add_message "EmptyMessage" do
    end
    add_message "Pong" do
      optional :ack, :string, 1
    end
    add_message "CallToBot" do
      optional :botId, :string, 1
      optional :parameter, :string, 2
    end
    add_message "BotResponse" do
      optional :response, :string, 1
    end
    add_message "BuildRequest" do
      optional :botId, :string, 1
      optional :language, :string, 2
      optional :code, :string, 3
    end
    add_message "BuildResponse" do
      optional :imageId, :string, 1
    end
    add_message "TurnMessage" do
      optional :parameter, :string, 1
    end
    add_message "PlayerResponse" do
      optional :response, :string, 1
    end
  end
end

EmptyMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("EmptyMessage").msgclass
Pong = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Pong").msgclass
CallToBot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CallToBot").msgclass
BotResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BotResponse").msgclass
BuildRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BuildRequest").msgclass
BuildResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BuildResponse").msgclass
TurnMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TurnMessage").msgclass
PlayerResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PlayerResponse").msgclass
