# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: playturn.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("playturn.proto", :syntax => :proto3) do
    add_message "EmptyMessage" do
    end
    add_message "Pong" do
      optional :ack, :string, 1
    end
    add_message "TurnMessage" do
      optional :parameter, :string, 1
    end
    add_message "PlayerResponse" do
      optional :response, :string, 1
    end
  end
end

EmptyMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("EmptyMessage").msgclass
Pong = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Pong").msgclass
TurnMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TurnMessage").msgclass
PlayerResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PlayerResponse").msgclass
