# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: playturn.proto for package ''

require 'grpc'
require 'playturn_pb'

module TurnCaller
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'TurnCaller'

    rpc :ping, ::EmptyMessage, ::Pong
    rpc :play, ::TurnMessage, ::PlayerResponse
  end

  Stub = Service.rpc_stub_class
end
