// Code generated by gRPC proto compiler.  DO NOT EDIT!
// source: playturn.proto

#import <Foundation/Foundation.h>

#if !defined(GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO) || !GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO
#import "Playturn.pbobjc.h"
#endif

#if !defined(GPB_GRPC_PROTOCOL_ONLY) || !GPB_GRPC_PROTOCOL_ONLY
#import <ProtoRPC/ProtoService.h>
#import <ProtoRPC/ProtoRPCLegacy.h>
#import <RxLibrary/GRXWriteable.h>
#import <RxLibrary/GRXWriter.h>
#endif

@class EmptyMessage;
@class PlayerResponse;
@class Pong;
@class TurnMessage;

#if !defined(GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO) || !GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO
#endif

@class GRPCUnaryProtoCall;
@class GRPCStreamingProtoCall;
@class GRPCCallOptions;
@protocol GRPCProtoResponseHandler;
@class GRPCProtoCall;


NS_ASSUME_NONNULL_BEGIN

@protocol TurnCaller2 <NSObject>

#pragma mark ping(EmptyMessage) returns (Pong)

- (GRPCUnaryProtoCall *)pingWithMessage:(EmptyMessage *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark play(TurnMessage) returns (PlayerResponse)

- (GRPCUnaryProtoCall *)playWithMessage:(TurnMessage *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

@end

/**
 * The methods in this protocol belong to a set of old APIs that have been deprecated. They do not
 * recognize call options provided in the initializer. Using the v2 protocol is recommended.
 */
@protocol TurnCaller <NSObject>

#pragma mark ping(EmptyMessage) returns (Pong)

- (void)pingWithRequest:(EmptyMessage *)request handler:(void(^)(Pong *_Nullable response, NSError *_Nullable error))handler;

- (GRPCProtoCall *)RPCTopingWithRequest:(EmptyMessage *)request handler:(void(^)(Pong *_Nullable response, NSError *_Nullable error))handler;


#pragma mark play(TurnMessage) returns (PlayerResponse)

- (void)playWithRequest:(TurnMessage *)request handler:(void(^)(PlayerResponse *_Nullable response, NSError *_Nullable error))handler;

- (GRPCProtoCall *)RPCToplayWithRequest:(TurnMessage *)request handler:(void(^)(PlayerResponse *_Nullable response, NSError *_Nullable error))handler;


@end


#if !defined(GPB_GRPC_PROTOCOL_ONLY) || !GPB_GRPC_PROTOCOL_ONLY
/**
 * Basic service implementation, over gRPC, that only does
 * marshalling and parsing.
 */
@interface TurnCaller : GRPCProtoService<TurnCaller2, TurnCaller>
- (instancetype)initWithHost:(NSString *)host callOptions:(GRPCCallOptions *_Nullable)callOptions NS_DESIGNATED_INITIALIZER;
+ (instancetype)serviceWithHost:(NSString *)host callOptions:(GRPCCallOptions *_Nullable)callOptions;
// The following methods belong to a set of old APIs that have been deprecated.
- (instancetype)initWithHost:(NSString *)host;
+ (instancetype)serviceWithHost:(NSString *)host;
@end
#endif

NS_ASSUME_NONNULL_END

