version: '3.9'

services:
  mongo:
    image: mongo:5.0
    container_name: xmartlake_mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@xmartlake_mongo:27017
    depends_on:
      - mongo

  bots_supervisor:
    build:
      context: ./bots_supervisor
    ports:
      - "50051:50051"
      - "8444:8443"
    environment:
      KUBERNETES_HOST: http://host.docker.internal:8444
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  bots_builder:
    container_name: bots_builder
    build:
      context: ./bots_builder
    ports:
      - "50050:50050"
      - "8443:8443"
    privileged: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  
  xmartlake_api:
    container_name: xmartlake_api
    build:
      context: ./coordinator
    ports:
      - 7000:7000
    environment:
      MONGO_CONNECTION_STRING: mongodb://admin:admin@mongo:27017/xmartlake

    depends_on:
      - mongo
      - bots_supervisor
