<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bots.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>BuildRequest</code>
 */
class BuildRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string botId = 1;</code>
     */
    protected $botId = '';
    /**
     * Generated from protobuf field <code>string language = 2;</code>
     */
    protected $language = '';
    /**
     * Generated from protobuf field <code>string code = 3;</code>
     */
    protected $code = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $botId
     *     @type string $language
     *     @type string $code
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bots::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string botId = 1;</code>
     * @return string
     */
    public function getBotId()
    {
        return $this->botId;
    }

    /**
     * Generated from protobuf field <code>string botId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBotId($var)
    {
        GPBUtil::checkString($var, True);
        $this->botId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string language = 2;</code>
     * @return string
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * Generated from protobuf field <code>string language = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLanguage($var)
    {
        GPBUtil::checkString($var, True);
        $this->language = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string code = 3;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>string code = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

}

