<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bots.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CallToBot</code>
 */
class CallToBot extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string botId = 1;</code>
     */
    protected $botId = '';
    /**
     * Generated from protobuf field <code>string parameter = 2;</code>
     */
    protected $parameter = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $botId
     *     @type string $parameter
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bots::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string botId = 1;</code>
     * @return string
     */
    public function getBotId()
    {
        return $this->botId;
    }

    /**
     * Generated from protobuf field <code>string botId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBotId($var)
    {
        GPBUtil::checkString($var, True);
        $this->botId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string parameter = 2;</code>
     * @return string
     */
    public function getParameter()
    {
        return $this->parameter;
    }

    /**
     * Generated from protobuf field <code>string parameter = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setParameter($var)
    {
        GPBUtil::checkString($var, True);
        $this->parameter = $var;

        return $this;
    }

}

