<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: playturn.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Pong</code>
 */
class Pong extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ack = 1;</code>
     */
    protected $ack = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ack
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Playturn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ack = 1;</code>
     * @return string
     */
    public function getAck()
    {
        return $this->ack;
    }

    /**
     * Generated from protobuf field <code>string ack = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAck($var)
    {
        GPBUtil::checkString($var, True);
        $this->ack = $var;

        return $this;
    }

}

