apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coordinator-ingress
spec:
  rules:
  - host: xmartlake.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: coordinator
            port:
              name: http
