apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: supervisor-rolebinding
subjects:
- kind: ServiceAccount
  name: supervisor-sa
roleRef:
  kind: Role
  name: supervisor-role
  apiGroup: rbac.authorization.k8s.io
