apiVersion: v1
kind: ServiceAccount
metadata:
  name: supervisor-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: supervisor-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/exec", "pods/proxy", "deployments"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "deletecollection", "patch", "exec"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "deletecollection", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]