# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: playturn.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eplayturn.proto\"\x0e\n\x0c\x45mptyMessage\"\x13\n\x04Pong\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t\" \n\x0bTurnMessage\x12\x11\n\tparameter\x18\x01 \x01(\t\"\"\n\x0ePlayerResponse\x12\x10\n\x08response\x18\x01 \x01(\t2Q\n\nTurnCaller\x12\x1c\n\x04ping\x12\r.EmptyMessage\x1a\x05.Pong\x12%\n\x04play\x12\x0c.TurnMessage\x1a\x0f.PlayerResponseb\x06proto3')



_EMPTYMESSAGE = DESCRIPTOR.message_types_by_name['EmptyMessage']
_PONG = DESCRIPTOR.message_types_by_name['Pong']
_TURNMESSAGE = DESCRIPTOR.message_types_by_name['TurnMessage']
_PLAYERRESPONSE = DESCRIPTOR.message_types_by_name['PlayerResponse']
EmptyMessage = _reflection.GeneratedProtocolMessageType('EmptyMessage', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMESSAGE,
  '__module__' : 'playturn_pb2'
  # @@protoc_insertion_point(class_scope:EmptyMessage)
  })
_sym_db.RegisterMessage(EmptyMessage)

Pong = _reflection.GeneratedProtocolMessageType('Pong', (_message.Message,), {
  'DESCRIPTOR' : _PONG,
  '__module__' : 'playturn_pb2'
  # @@protoc_insertion_point(class_scope:Pong)
  })
_sym_db.RegisterMessage(Pong)

TurnMessage = _reflection.GeneratedProtocolMessageType('TurnMessage', (_message.Message,), {
  'DESCRIPTOR' : _TURNMESSAGE,
  '__module__' : 'playturn_pb2'
  # @@protoc_insertion_point(class_scope:TurnMessage)
  })
_sym_db.RegisterMessage(TurnMessage)

PlayerResponse = _reflection.GeneratedProtocolMessageType('PlayerResponse', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERRESPONSE,
  '__module__' : 'playturn_pb2'
  # @@protoc_insertion_point(class_scope:PlayerResponse)
  })
_sym_db.RegisterMessage(PlayerResponse)

_TURNCALLER = DESCRIPTOR.services_by_name['TurnCaller']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTYMESSAGE._serialized_start=18
  _EMPTYMESSAGE._serialized_end=32
  _PONG._serialized_start=34
  _PONG._serialized_end=53
  _TURNMESSAGE._serialized_start=55
  _TURNMESSAGE._serialized_end=87
  _PLAYERRESPONSE._serialized_start=89
  _PLAYERRESPONSE._serialized_end=123
  _TURNCALLER._serialized_start=125
  _TURNCALLER._serialized_end=206
# @@protoc_insertion_point(module_scope)
