apiVersion: v1
kind: Service
metadata:
  name: controller-service
spec:
  selector:
    app: controller
  ports:
  - name: http
    port: 80
    targetPort: http-external
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: builder
spec:
  selector:
    app: builder
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: controller
spec:
  selector:
    app: controller
  ports:
  - name: http-internal
    port: 7000
    targetPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: supervisor
spec:
  selector:
    app: supervisor
  ports:
  - name: http
    port: 80
    targetPort: 8080
