apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator
spec:
  selector:
    matchLabels:
      app: coordinator
  replicas: 1
  template:
    metadata:
      labels:
        app: coordinator
    spec:
      containers:
      - name: coordinator
        image: coordinator:latest
        imagePullPolicy: Never
      - name: http-internal
        containerPort: 7000
      env:
      - name: SUPERVISOR_ADDRESS
        value: "supervisor:50050"
      - name: BUILDER_ADDRESS
        value: "builder:50050"
---
apiVersion: v1
kind: Service
metadata:
  name: coordinator
spec:
  selector:
    app: coordinator
  ports:
  - name: http
    port: 80
    targetPort: 7000
  type: LoadBalancer
