# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bots.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bots.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nbots.proto\"\x0e\n\x0c\x45mptyMessage\"\x13\n\x04Pong\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t\"-\n\tCallToBot\x12\r\n\x05\x62otId\x18\x01 \x01(\t\x12\x11\n\tparameter\x18\x02 \x01(\t\"\x1f\n\x0b\x42otResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"=\n\x0c\x42uildRequest\x12\r\n\x05\x62otId\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\" \n\rBuildResponse\x12\x0f\n\x07imageId\x18\x01 \x01(\t\" \n\x0bTurnMessage\x12\x11\n\tparameter\x18\x01 \x01(\t\"\"\n\x0ePlayerResponse\x12\x10\n\x08response\x18\x01 \x01(\t2L\n\nBotManager\x12\x1c\n\x04ping\x12\r.EmptyMessage\x1a\x05.Pong\x12 \n\x04\x63\x61ll\x12\n.CallToBot\x1a\x0c.BotResponse2Y\n\x0c\x42uildManager\x12\x1c\n\x04ping\x12\r.EmptyMessage\x1a\x05.Pong\x12+\n\nbuildimage\x12\r.BuildRequest\x1a\x0e.BuildResponse2Q\n\nTurnCaller\x12\x1c\n\x04ping\x12\r.EmptyMessage\x1a\x05.Pong\x12%\n\x04play\x12\x0c.TurnMessage\x1a\x0f.PlayerResponseb\x06proto3'
)




_EMPTYMESSAGE = _descriptor.Descriptor(
  name='EmptyMessage',
  full_name='EmptyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=28,
)


_PONG = _descriptor.Descriptor(
  name='Pong',
  full_name='Pong',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ack', full_name='Pong.ack', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=49,
)


_CALLTOBOT = _descriptor.Descriptor(
  name='CallToBot',
  full_name='CallToBot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='botId', full_name='CallToBot.botId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parameter', full_name='CallToBot.parameter', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=96,
)


_BOTRESPONSE = _descriptor.Descriptor(
  name='BotResponse',
  full_name='BotResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='BotResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=129,
)


_BUILDREQUEST = _descriptor.Descriptor(
  name='BuildRequest',
  full_name='BuildRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='botId', full_name='BuildRequest.botId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='language', full_name='BuildRequest.language', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='BuildRequest.code', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=192,
)


_BUILDRESPONSE = _descriptor.Descriptor(
  name='BuildResponse',
  full_name='BuildResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageId', full_name='BuildResponse.imageId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=226,
)


_TURNMESSAGE = _descriptor.Descriptor(
  name='TurnMessage',
  full_name='TurnMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='parameter', full_name='TurnMessage.parameter', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=260,
)


_PLAYERRESPONSE = _descriptor.Descriptor(
  name='PlayerResponse',
  full_name='PlayerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='PlayerResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=296,
)

DESCRIPTOR.message_types_by_name['EmptyMessage'] = _EMPTYMESSAGE
DESCRIPTOR.message_types_by_name['Pong'] = _PONG
DESCRIPTOR.message_types_by_name['CallToBot'] = _CALLTOBOT
DESCRIPTOR.message_types_by_name['BotResponse'] = _BOTRESPONSE
DESCRIPTOR.message_types_by_name['BuildRequest'] = _BUILDREQUEST
DESCRIPTOR.message_types_by_name['BuildResponse'] = _BUILDRESPONSE
DESCRIPTOR.message_types_by_name['TurnMessage'] = _TURNMESSAGE
DESCRIPTOR.message_types_by_name['PlayerResponse'] = _PLAYERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptyMessage = _reflection.GeneratedProtocolMessageType('EmptyMessage', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMESSAGE,
  '__module__' : 'bots_pb2'
  # @@protoc_insertion_point(class_scope:EmptyMessage)
  })
_sym_db.RegisterMessage(EmptyMessage)

Pong = _reflection.GeneratedProtocolMessageType('Pong', (_message.Message,), {
  'DESCRIPTOR' : _PONG,
  '__module__' : 'bots_pb2'
  # @@protoc_insertion_point(class_scope:Pong)
  })
_sym_db.RegisterMessage(Pong)

CallToBot = _reflection.GeneratedProtocolMessageType('CallToBot', (_message.Message,), {
  'DESCRIPTOR' : _CALLTOBOT,
  '__module__' : 'bots_pb2'
  # @@protoc_insertion_point(class_scope:CallToBot)
  })
_sym_db.RegisterMessage(CallToBot)

BotResponse = _reflection.GeneratedProtocolMessageType('BotResponse', (_message.Message,), {
  'DESCRIPTOR' : _BOTRESPONSE,
  '__module__' : 'bots_pb2'
  # @@protoc_insertion_point(class_scope:BotResponse)
  })
_sym_db.RegisterMessage(BotResponse)

BuildRequest = _reflection.GeneratedProtocolMessageType('BuildRequest', (_message.Message,), {
  'DESCRIPTOR' : _BUILDREQUEST,
  '__module__' : 'bots_pb2'
  # @@protoc_insertion_point(class_scope:BuildRequest)
  })
_sym_db.RegisterMessage(BuildRequest)

BuildResponse = _reflection.GeneratedProtocolMessageType('BuildResponse', (_message.Message,), {
  'DESCRIPTOR' : _BUILDRESPONSE,
  '__module__' : 'bots_pb2'
  # @@protoc_insertion_point(class_scope:BuildResponse)
  })
_sym_db.RegisterMessage(BuildResponse)

TurnMessage = _reflection.GeneratedProtocolMessageType('TurnMessage', (_message.Message,), {
  'DESCRIPTOR' : _TURNMESSAGE,
  '__module__' : 'bots_pb2'
  # @@protoc_insertion_point(class_scope:TurnMessage)
  })
_sym_db.RegisterMessage(TurnMessage)

PlayerResponse = _reflection.GeneratedProtocolMessageType('PlayerResponse', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERRESPONSE,
  '__module__' : 'bots_pb2'
  # @@protoc_insertion_point(class_scope:PlayerResponse)
  })
_sym_db.RegisterMessage(PlayerResponse)



_BOTMANAGER = _descriptor.ServiceDescriptor(
  name='BotManager',
  full_name='BotManager',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=298,
  serialized_end=374,
  methods=[
  _descriptor.MethodDescriptor(
    name='ping',
    full_name='BotManager.ping',
    index=0,
    containing_service=None,
    input_type=_EMPTYMESSAGE,
    output_type=_PONG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='call',
    full_name='BotManager.call',
    index=1,
    containing_service=None,
    input_type=_CALLTOBOT,
    output_type=_BOTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BOTMANAGER)

DESCRIPTOR.services_by_name['BotManager'] = _BOTMANAGER


_BUILDMANAGER = _descriptor.ServiceDescriptor(
  name='BuildManager',
  full_name='BuildManager',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=376,
  serialized_end=465,
  methods=[
  _descriptor.MethodDescriptor(
    name='ping',
    full_name='BuildManager.ping',
    index=0,
    containing_service=None,
    input_type=_EMPTYMESSAGE,
    output_type=_PONG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='buildimage',
    full_name='BuildManager.buildimage',
    index=1,
    containing_service=None,
    input_type=_BUILDREQUEST,
    output_type=_BUILDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BUILDMANAGER)

DESCRIPTOR.services_by_name['BuildManager'] = _BUILDMANAGER


_TURNCALLER = _descriptor.ServiceDescriptor(
  name='TurnCaller',
  full_name='TurnCaller',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=467,
  serialized_end=548,
  methods=[
  _descriptor.MethodDescriptor(
    name='ping',
    full_name='TurnCaller.ping',
    index=0,
    containing_service=None,
    input_type=_EMPTYMESSAGE,
    output_type=_PONG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='play',
    full_name='TurnCaller.play',
    index=1,
    containing_service=None,
    input_type=_TURNMESSAGE,
    output_type=_PLAYERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TURNCALLER)

DESCRIPTOR.services_by_name['TurnCaller'] = _TURNCALLER

# @@protoc_insertion_point(module_scope)
