# --- Board Settings
DEFAULT_WIDTH = 100
DEFAULT_HEIGHT = 100
DEFAULT_STOP_LIMIT = 1000
NORMAL_SIZE_LIMIT = 800  # Set how many turns in normal size board

# --- Player settings
DEFAULT_FUEL = 100
DEFAULT_HEALTH = 100
DEFAULT_BULLETS = 100

# --- Game
REFUEL_BY_TURN = 20
RELOAD_BY_TURN = 20
REPAIR_BY_TURN = 20

FUEL_CONSUMED_BY_TURN = 1
FUEL_CONSUMED_BY_TURN_WITH_SHIELD = 2
DAMAGE_BY_HIT = 10
DAMAGE_BY_BULLET = 25
SHIELD_PROTECTION_PERCENTAGE = 50


# --- Environment
DEFAULT_VISIBILY_DISTANCE = 2
FOE_IDENTIFICATION = "F"
WALL_IDENTIFICATION = "W"
