# --- Board Settings
DEFAULT_WIDTH = 40
DEFAULT_HEIGHT = 40
DEFAULT_STOP_LIMIT = 500
NORMAL_SIZE_LIMIT = 20  # Set how many turns in normal size board
DECREMENT_AFTER_LIMIT = 5

# --- Player settings
DEFAULT_FUEL = 10
DEFAULT_HEALTH = 5
DEFAULT_BULLETS = 25

# --- Game
REFUEL_BY_TURN = 4
RELOAD_BY_TURN = 5
REPAIR_BY_TURN = 1

FUEL_CONSUMED_BY_TURN = 1
FUEL_CONSUMED_BY_TURN_WITH_SHIELD = 2
DAMAGE_BY_HIT = 10
DAMAGE_BY_BULLET = 25
SHIELD_PROTECTION_PERCENTAGE = 50
MAX_HEALTH = 99
MAX_BULLET = 99
MAX_FUEL = 99


# --- Environment
DEFAULT_VISIBILY_DISTANCE = 3
FOE_SYMBOL = "F"
WALL_SYMBOL = "W"
PLAYER_POSITION_IDENTIFICACION = "X"
DEFAULT_EMPTY_PLACE_SYMBOL = "."
